### ISSUE TITLE
Show file from disk, if available immediatally and override with fresh data from dropbox.

### ISSUE THREAD

**Issue by doozMen** [icapps/ios_lottie_dropper#6]
Now `DropboxBrowserViewModel` has function to load files. `DropboxDetailViewModel` load the file and saves it to disk. Reuse stored file.

So download does:

1. Load a file without any existing file -> done called once
2. Load file when previous exists -> call done immediately and again after reload
3. Extra: Check for diff of file 

```swift
- (void) downloadFile:(void (^) (void)) done {

	NSFileManager *fileManager = [NSFileManager defaultManager];
	NSURL *outputDirectory = [fileManager URLsForDirectory:NSDocumentDirectory inDomains:NSUserDomainMask][0];
	_fileOnDisk = [outputDirectory URLByAppendingPathComponent:self.file.pathLower]; // reuse this file if available

	// ...
}
```

Voor de korte uitleg:
**zie dropbox**

**Comment by Periteus** [comment]
TODO: 

1. Check why downloadFile does not instantiate call when no internet connection
